module.exports = {
  ITEM_PUT_FORBIDDEN: 'ITEM_PUT_FORBIDDEN',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_STATUS_FORBIDDEN: 'ORDER_STATUS_FORBIDDEN',
  VENDOR_UPGRADE_FAILED: 'VENDOR_UPGRADE_FAILED',
};
